<?php
$this->_prepareData();
$count	 = 1;
$limit	 = $this->getItemLimit();
?>
<?php if (count($this->getItemCollection()) > 0): ?>
	<?php if (count($this->getItemCollection()->getItems())): ?>
		<?php $_columnCount = $this->getColumnCount(); ?>
		<div class="box-recommendation">
			<h2><?php echo $this->getWidgetTitle() ?></h2>
			<ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col" id="upsell-product-table">
				<?php $this->resetItemsIterator() ?>
				<?php foreach ($this->getItemCollection()->getItems() as $_link): ?>
					<li <?php if ($this->getStyleAppearance() === 'horizontal')?> class="item" >
						<a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_link->getName()) ?>">
							<img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize($this->getThumbnailSize()) ?>" alt="<?php echo $this->escapeHtml($_link->getName()) ?>" class="product-image"/>
						</a>
						<div class="product-name" style="text-align: center;"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_link->getName()) ?>"><?php echo $this->escapeHtml($_link->getName()) ?></a></div>
						<div class="price-box" style="text-align: center;"><?php echo $this->getPriceHtml($_link, true, '-upsell') ?></div>
						<?php echo $this->getReviewsSummaryHtml($_link) ?>
					</li>

					<?php
					if (($count) >= $limit)
						break;
					$count++;
				endforeach;
				?>
			</ul>
		</div>
		<?php
	endif;
endif;
?>
